### ISSUE TITLE
Pacotes plonegovbr deveriam ter mais de um job de testes e templates de PR e issues

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.vlibrasvideo#24]
Da forma como o buildout.cfg dos pacotes hoje é feito, ficamos presos a um release e só temos integração contínua "de verdade" quando um novo release está pra ser lançado e trocamos a versão.

A desvantagem disso é que pode ocorrer de, no lançamento de um release, o pacote ter um erro e isso tem de ser consertado: isso meio que invalida a lógica de integração contínua, que é a de visualizar os erros quando eles aparecem. Ao mesmo tempo, é útil sim testarmos com o próximo release pois alguma pinagem pode influenciar nos testes e também deve ser visto.

https://raw.githubusercontent.com/plonegovbr/portal.buildout/master/buildout.d/versions.cfg passa a conter as pinagens que deverão constar num novo release. Dessa forma, todos os pacotes devem ter, como última linha do extends, essa url. Esse é o job padrão: referencia sempre as versões de um release ainda pendente.
ex(buildout.cfg):

``` cfg
[buildout]
extends =
    https://raw.github.com/collective/buildout.plonetest/master/test-4.3.x.cfg
    https://raw.github.com/collective/buildout.plonetest/master/qa.cfg
    https://raw.githubusercontent.com/plone/plone.app.robotframework/master/versions.cfg
    https://raw.githubusercontent.com/plonegovbr/portal.buildout/master/buildout.d/versions.cfg
```

O segundo job, via sed, remove essa linha, dessa forma, pega diretamente do master. O que pega do master pode falhar, ver como o collective.cover faz isso.
ex(no travis.yml):

``` yml
env:
  matrix:
    - MASTER=true
    - PENDING_RELEASE=true
matrix:
  allow_failures:
    - env: MASTER=true
  fast_finish: true
install:
- test $MASTER && sed -ie '/https:\/\/raw\.githubusercontent\.com\/plonegovbr\/portal\.buildout\/master\/buildout\.d\/versions\.cfg/d' buildout.cfg || true
```

Como no caso do vlibrasnews já _são testadas várias versões de Plone_, a forma acima não atende aos seus requisitos: dessa forma, recomendamos como o brasil.gov.barra está fazendo atualmente:

https://github.com/plonegovbr/brasil.gov.barra/blob/8b214af16e192c5d4dc8f9c7a99381ae6c4285aa/.travis.yml

https://github.com/plonegovbr/brasil.gov.barra/blob/8b214af16e192c5d4dc8f9c7a99381ae6c4285aa/buildout.cfg

A maior motivação dessa alteração, como falado, é poder garantir que os testes passam num futuro release e já testar no MASTER.

https://github.com/plonegovbr/portalpadrao.release/issues/11
